### ISSUE TITLE
Delete site (with recordings) isn't working

### ISSUE THREAD

**Issue by koonchaya** [rfcx/arbimon#2118]
From: [wendy.estes-zumpf@wyo.gov](mailto:wendy.estes-zumpf@wyo.gov)

Delete selected sites on Site page isn't working. This only happens with the site with recordings.
![Image](https://github.com/user-attachments/assets/42924733-632f-46fb-acdf-281848df74fa)
![Image](https://github.com/user-attachments/assets/d8c2e689-3cec-4e24-bf70-b43e0140df70)
![Image](https://github.com/user-attachments/assets/7ed37499-7208-4e4f-867c-599b050688fa)

**Comment by RatreeOchn** [comment]
```
--deleteRecordingInAnalyses recIds [ 185070286 ]
ALERT: connection taken for query DELETE FROM pattern_matching_rois_new WHERE recording_id in (185070286) is not freed after 25000
ALERT: request to "/legacy-api/project/afffflll/sites/delete" did not finish in the treshold 35000
err Error: ER_LOCK_WAIT_TIMEOUT: Lock wait timeout exceeded; try restarting transaction
    at Query.Sequence._packetToError (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/sequences/Sequence.js:47:14)
    at Query.ErrorPacket (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/sequences/Query.js:79:18)
    at Protocol._parsePacket (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/Protocol.js:291:23)
    at Parser._parsePacket (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/Parser.js:433:10)
    at Parser.write (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/Parser.js:43:10)
    at Protocol.write (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/Protocol.js:38:16)
    at Socket.<anonymous> (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/Connection.js:88:28)
    at Socket.<anonymous> (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/Connection.js:526:10)
    at Socket.emit (node:events:369:20)
    at Socket.emit (node:domain:470:12)
    --------------------
    at Protocol._enqueue (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/protocol/Protocol.js:144:48)
    at PoolConnection.query (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/mysql/lib/Connection.js:198:25)
    at PoolConnection.connection.query (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/utils/dbpool.js:61:26)
    at Object.queryWithConnHandler (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/utils/dbpool.js:125:32)
    at processTicksAndRejections (node:internal/process/task_queues:76:11)
From previous event:
    at Object.dbpool.queryWithConn (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/utils/dbpool.js:155:87)
    at executeQuery (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:667:59)
    at Object.deleteRecordingInAnalyses (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:669:19)
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:640:36
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
From previous event:
    at Object.removeSite (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:629:14)
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/app/routes/data-api/project/sites.js:112:17
    at Layer.handle [as handle_request] (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/index.js:335:12) {
  code: 'ER_LOCK_WAIT_TIMEOUT',
  errno: 1205,
  sqlMessage: 'Lock wait timeout exceeded; try restarting transaction',
  sqlState: 'HY000',
  index: 0,
  sql: 'DELETE FROM pattern_matching_rois_new WHERE recording_id in (185070286)'
}
Error: Failed to delete site
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:656:23
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)
From previous event:
    at Object.removeSite (/Users/ratree/Documents/RFCx_work/arbimon-legacy/app/model/sites.js:650:19)
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/app/routes/data-api/project/sites.js:112:17
    at Layer.handle [as handle_request] (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/layer.js:95:5)
    at /Users/ratree/Documents/RFCx_work/arbimon-legacy/node_modules/express/lib/router/index.js:281:22
error: POST 500 /legacy-api/project/afffflll/sites/delete Response Time: 53002 Authorization: undefined Email: oncha.tree@gmail.com Body: {"sites":[57447]} {"meta":{}}
```
